services:
  amplifier.warehouse.api:
    image: amplifier.warehouse.api
    build:
      context: .
      dockerfile: Amplifier.WareHouse.API/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - data_access_network
  
  amplifier.warehouse.mssql_database:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    env_file:
      - ./mssql_database.env
    ports:
      - "1433:1433"
    networks:
      - data_access_network
    volumes:
      - mssql_data:/var/opt/mssql

        
networks:
  data_access_network:
    driver: 
      bridge

volumes:
  mssql_data:      
